[cgv_event_special]
title = "CGV ─ 이벤트 ─ SPECIAL"
url = "http://www.cgv.co.kr/culture-event/event/defaultNew.aspx?mCode=001"
entrySelector = "ul.cf li"
titleSelector = "p.txt1"
linkSelector = "a[id='tile_3']"
contentSelector = "p.txt2"
imageSelector = "div.evt-thumb img"
waitUntil = "networkidle"

[cgv_event_reservation]
title = "CGV ─ 이벤트 ─ 영화 예매"
url = "http://www.cgv.co.kr/culture-event/event/defaultNew.aspx?mCode=004"
entrySelector = "ul.cf li"
titleSelector = "p.txt1"
linkSelector = "a[id='tile_3']"
contentSelector = "p.txt2"
imageSelector = "div.evt-thumb img"
waitUntil = "networkidle"

[cgv_event_membership]
title = "CGV ─ 이벤트 ─ 멤버십 CLUB"
url = "http://www.cgv.co.kr/culture-event/event/defaultNew.aspx?mCode=008"
entrySelector = "ul.cf li"
titleSelector = "p.txt1"
linkSelector = "a[id='tile_3']"
contentSelector = "p.txt2"
imageSelector = "div.evt-thumb img"
waitUntil = "networkidle"

[cgv_event_theather]
title = "CGV ─ 이벤트 ─ CGV 극장별"
url = "http://www.cgv.co.kr/culture-event/event/defaultNew.aspx?mCode=005"
entrySelector = "ul.cf li"
titleSelector = "p.txt1"
linkSelector = "a[id='tile_3']"
contentSelector = "p.txt2"
imageSelector = "div.evt-thumb img"
waitUntil = "networkidle"

[cgv_event_partnership]
title = "CGV ─ 이벤트 ─ 제휴 할인"
url = "http://www.cgv.co.kr/culture-event/event/defaultNew.aspx?mCode=006"
entrySelector = "ul.cf li"
titleSelector = "p.txt1"
linkSelector = "a[id='tile_3']"
contentSelector = "p.txt2"
imageSelector = "div.evt-thumb img"
waitUntil = "networkidle"

[megabox_event_pick]
title = "메가박스 ─ 이벤트 ─ 메가Pick"
url = "https://www.megabox.co.kr/event/megabox"
entrySelector = "div.event-list ul li"
titleSelector = "p.tit"
linkSelector = "a"
contentSelector = "p.date"
imageSelector = "p.img img"
waitUntil = "networkidle"

[megabox_event_movie]
title = "메가박스 ─ 이벤트 ─ 영화"
url = "https://www.megabox.co.kr/event/movie"
entrySelector = "div.event-list ul li"
titleSelector = "p.tit"
linkSelector = "a[data-no]"
contentSelector = "p.date"
imageSelector = "p.img img"
waitUntil = "networkidle"

[megabox_event_theater]
title = "메가박스 ─ 이벤트 ─ 극장"
url = "https://www.megabox.co.kr/event/theater"
entrySelector = "div.event-list ul li"
titleSelector = "p.tit"
linkSelector = "a[data-no]"
contentSelector = "p.date"
imageSelector = "p.img img"
waitUntil = "networkidle"

[megabox_event_promotion]
title = "메가박스 ─ 이벤트 ─ 제휴 할인"
url = "https://www.megabox.co.kr/event/promotion"
entrySelector = "div.event-list ul li"
titleSelector = "p.tit"
linkSelector = "a[data-no]"
contentSelector = "p.date"
imageSelector = "p.img img"
waitUntil = "networkidle"

[megabox_event_curtaincall]
title = "메가박스 ─ 이벤트 ─ 시사회 무대인사"
url = "https://www.megabox.co.kr/event/curtaincall"
entrySelector = "div.event-list ul li"
titleSelector = "p.tit"
linkSelector = "a[data-no]"
contentSelector = "p.date"
imageSelector = "p.img img"
waitUntil = "networkidle"

[lottecinema_event_movie]
title = "롯데시네마 ─ 이벤트 ─ 영화"
url = "https://event.lottecinema.co.kr/NLCHS/Event/DetailList?code=20"
entrySelector = "ul.img_lst_wrap li"
titleSelector = "div.itm_date"
linkSelector = "a"
imageSelector = "img"
waitUntil = "networkidle"

[lottecinema_event_curtaincall]
title = "롯데시네마 ─ 이벤트 ─ 시사회 무대인사"
url = "https://event.lottecinema.co.kr/NLCHS/Event/DetailList?code=40"
entrySelector = "ul.img_lst_wrap li"
titleSelector = "div.itm_date"
linkSelector = "a"
imageSelector = "img"
waitUntil = "networkidle"

[lottecinema_event_hot]
title = "롯데시네마 ─ 이벤트 ─ HOT"
url = "https://event.lottecinema.co.kr/NLCHS/Event/DetailList?code=10"
entrySelector = "ul.img_lst_wrap li"
titleSelector = "div.itm_date"
linkSelector = "a"
imageSelector = "img"
waitUntil = "networkidle"

[lottecinema_event_promotion]
title = "롯데시네마 ─ 이벤트 ─ 제휴할인"
url = "https://event.lottecinema.co.kr/NLCHS/Event/DetailList?code=50"
entrySelector = "ul.img_lst_wrap li"
titleSelector = "div.itm_date"
linkSelector = "a"
imageSelector = "img"
waitUntil = "networkidle"

[extmovie_event]
title = "익스트림무비 ─ 시사회 ─ 시사회진행"
url = "https://extmovie.com/sisaing"
entrySelector = "ul li.list_unit"
titleSelector = "a.title_link"
linkSelector = "a.list_thumb"
imageSelector = "a.list_thumb img"
contentSelector = "p.list_summary"
waitUntil = "networkidle"
